services:
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
  frontend:
    build:
      context: ./todo-frontend
      dockerfile: ./Dockerfile # This will simply tell which dockerfile to read
    volumes:
     - ./todo-frontend/:/usr/src/app/ # The path can be relative, so ./ is enough to say "the same location as the docker-compose.yml"
    ports:
      - 3001:3001
    container_name: todo-front # This will name the container hello-front
  debug-helper:
    image: busybox
    
  mongo:
     image: mongo
     ports:
      - 3456:27017
     environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
     volumes:
       - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
  redis_db:
    image: redis:6.2.6
    ports:
      - 6379:6379
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
       - ./todo-backend/redis_data:/data
       
  backend:
    build:
      context: ./todo-backend
      dockerfile: Dockerfile
    volumes:
       - ./todo-backend:/usr/src/app/
    ports:
      - 3000:3000
    container_name: todo-backend
    environment: 
      - REDIS_URL=http://todo-backend_redis_1:6379
      - MONGO_URL=mongodb://the_username:the_password@todo-backend_mongo_1/the_database 
