services:
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
  frontend:
    build:
      context: ./excercise2.6
      dockerfile: ./Dockerfile # This will simply tell which dockerfile to read
    volumes:
     - ./excercise2.6/:/usr/src/app/ # The path can be relative, so ./ is enough to say "the same location as the docker-compose.yml"
    ports:
      - 3001:3001
    container_name: note-front # This will name the container hello-front
  debug-helper:
    image: busybox      
  backend:
    build:
      context: ./full-stackPart3
      dockerfile: Dockerfile
    volumes:
       - ./full-stackPart3:/usr/src/app/
    ports:
      - 3000:3000
    container_name: note-backend
